application: notify
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /list
  script: admin.py
  login: admin
  secure: required

- url: /post
  script: admin.py
  login: admin
  secure: required

- url: /.*
  script: main.py
