application: notify
version: 1
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^README.rst$

handlers:
- url: /css
  static_dir: css

- url: /list
  script: main.py
  login: admin

- url: /post
  script: main.py
  login: admin

- url: /.*
  script: main.py
